### ISSUE TITLE
iOS problem

### ISSUE THREAD

**Issue by AtixD** [bradmartin/nativescript-cardview#10]
Problem build on iOS
![2016-03-02 16 39 43](https://cloud.githubusercontent.com/assets/17594120/13461895/7ace8fec-e095-11e5-90eb-92097afeb57e.png)

**Comment by bradmartin** [comment]
@nathanwalker - can you help out here?

**Comment by NathanWalker** [comment]
@AtixD There's still some issues with XCode and CocoaPods and `tns`.
After the build fails from the command-line, go into 'platforms/ios' and open the `.xcworkspace` file (**not** the `.xcodeproj`).
Then set your target to the 2nd one like this for example:
<img width="695" alt="screen shot 2016-02-25 at 9 46 33 pm" src="https://cloud.githubusercontent.com/assets/457187/13466889/d5b171da-e050-11e5-96af-a0d6a00d6171.png">

Then run that from XCode and it should build just fine.
Let me know.

**Comment by AtixD** [comment]
@NathanWalker  Working. Thank you! 
In the future, it will be corrected?
////////////////////////////////////////////////////////
if you add a picture from a remote source on iOS ->
![2016-03-02 22 58 19](https://cloud.githubusercontent.com/assets/17594120/13473422/5de430b4-e0ca-11e5-8d08-1c268bb29fce.png)
if it is adjusted locally ->
![2016-03-02 23 01 30](https://cloud.githubusercontent.com/assets/17594120/13473513/bf7308d2-e0ca-11e5-9ca0-0ac9232bb10a.png)
On android I do not observe this problem

**Comment by NathanWalker** [comment]
@AtixD Great to hear. Cheers!

I believe it will be corrected in the future. I'm keeping an eye out for it!

**Comment by Headcult** [comment]
@NathanWalker @bradmartin Seeing this closed issue a little bit late. I faced the same issue on TNS v2.0  using Xcode 7.2.1 with CocoaPods v1.0 on my Mac OS X Yosemite 10.10.5. Read about it online and reverted my Xcode to 7.1.1 where it got deployed successfully onto the iOS 9.2 Simulator (iPhone 6s).

**Comment by NathanWalker** [comment]
@Headcult XCode 7.3 works as well, just upgrade, and then downgrade your CocoaPods to `0.39.0`.

**Comment by NathanWalker** [comment]
Ensure you set the `backgroundColor` on your card as that is needed so:

```
<Card:CardView class="cardStyle" margin="10" elevation="40" radius="5" backgroundColor="#fff">
           <grid-layout rows="200, auto, auto" columns="auto, auto, *">
               <image src="~/images/batman.jpg" stretch="aspectFill" colSpan="3" row="0" />
               <label text="Batman wants to be friends?" class="info" textWrap="true" row="1" colSpan="3" />          
               <button text="DECLINE" tap="goAway" row="2" col="0" />
               <button text="ACCEPT" row="2" col="1" />
           </grid-layout>
       </Card:CardView>
```
