### ISSUE TITLE
Android 5.1.1, {N} 1.7.1, CardView strange

### ISSUE THREAD

**Issue by NathanWalker** [bradmartin/nativescript-cardview#15]
I'm seeing this with the current state of the plugin with those versions?

<img width="434" alt="screen shot 2016-04-14 at 8 22 02 pm" src="https://cloud.githubusercontent.com/assets/457187/14550578/b21a99e0-027e-11e6-9d45-cb3f5abb864a.png">

**Comment by Headcult** [comment]
Yeah, me too, the Material Cards are not elevated and the drop shadow is not seen on v6.0 too. Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/11834518/14606680/e49106d2-059b-11e6-96f5-231d0c959619.png)

**Comment by bradmartin** [comment]
https://github.com/NativeScript/NativeScript/issues/1899

After 2.0 release I'll look into this. That should resolve the issue unless there are more cases for layering.

**Comment by bradmartin** [comment]
Closing this, I created a new app with NS version 2.0 and tns-core-modules @ 2.0.0 and everything looks okay with android 5.1 and 6.0.

If anyone has any issues with the latest platform I'll look into it again but everything should be fine.

**Comment by Headcult** [comment]
Hi @bradmartin, Can I know where to look for the NS 2.0 version of the Card-View plugin. I deployed this app today and it's the same. The card elevation is missing and the buttons are looking different. Thanks for the plugin though.

**Comment by bradmartin** [comment]
This was working with 2.0 when I last commented. What runtimes are you using and are you using the latest core-modules in your app? You might need to do a new build and try uninstalling and doing a new install of this plugin `npm i nativescript-cardview` to make sure the old version isn't cached in your app's node_modules. Also check the package.json dependencies to make sure it's not locked in an older version :) Let me know if you have any other questions. If you do I'll test it again but it should be working fine unless NativeScript changed something with their layouts again in 2.0.1 (the minor patch released last week).

**Comment by Headcult** [comment]
Yes, it's working as a plugin, in fact, I'm a big fan of the FAB and this plugin has just made me like NativeScript even more. A minor comment, can the elevation of the FAB be increased from our side as the shadow effect is barely visible.

What I was referring to here was the Demo app in this Github repo, this is still referring to an older TNS version. I thought this Demo app was also updated to TNS 2.0. No issues, otherwise, Thanks!
