### ISSUE TITLE
Cardview using in ListView or Repeater has no drop shadow on Android.

### ISSUE THREAD

**Issue by firecube** [bradmartin/nativescript-cardview#18]
Hi,

I presume this is a limitation in the nativescript controls but when I have a card view inside a list view or a repeater the cards have no drop shadow.  

I had to wrap the card in a StackLayout with padding otherwise the cards were right on top of each other on iOS but I have tried without this and still have the same behaviour.

Thanks, Simon

**Comment by bradmartin** [comment]
Send some screens and layout code you have to reproduce it. I have a drop
shadow in my listview, add a little padding to the cards and it looks okay.
It might be an issue with your layout specifically so let me know and I'll
try to help out.

**Comment by matt4446** [comment]
@firecube I had a similar problem. Try giving it a [margin](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/controls/card/card.control.ts#L12).

**Comment by firecube** [comment]
Thanks @matt4446 that was it!

**Comment by hackerunet** [comment]
Hi there, I know it's been a while, but I'm trying to restyle my ListView to replace each item for a fancy card with drop shadow but, I got no drop shadow and I cannot hide each item divider , the divider is always there, can you tell me how to hide each ListView item divider??
Thanks

**Comment by bradmartin** [comment]
@hackerunet - there is `separatorColor` property on listview (https://docs.nativescript.org/api-reference/globals look for the listview class here), you can color it to blend it into your background if you want. There are ways to remove it, just not sure at this moment.
