### ISSUE TITLE
working on iOS support

### ISSUE THREAD

**Issue by NathanWalker** [bradmartin/nativescript-cardview#2]
Nice plugin, my work is looking forward to having both platforms with this, thank you.
I've been trying to work with Pods and using this as a guide:
http://docs.nativescript.org/plugins/cocoapods

I'm having an issue getting it to work. If you get a chance to check it out here maybe we can work together on it:
https://github.com/NathanWalker/nativescript-cardview/tree/ios-support

Just a couple pointers on how to get the pod integration working and I could get past this road block.

**Comment by NathanWalker** [comment]
From within `demo` folder, using `tns add plugin plugins/`, it adds the pod reference correctly it looks like. But then when running `tns build ios`, I get the following (in short - it's a rather long chain of errors related to the `MaterialCardView` Pod):

```
/Users/nathan/Documents/github/nativescript-stuff/nativescript-cardview/demo/platforms/ios/Pods/MaterialCardView/MaterialCardView/MaterialCardView.swift:125:20: warning: overriding initializer parameter of type 'AnyObject' with implicitly unwrapped optional type 'AnyObject!'
    override init!(layer: AnyObject!) {
                   ^      ~~~~~~~~~~
/Users/nathan/Documents/github/nativescript-stuff/nativescript-cardview/demo/platforms/ios/Pods/MaterialCardView/MaterialCardView/MaterialCardView.swift:125:36: note: remove '!' to make the parameter required
    override init!(layer: AnyObject!) {
                                   ^

/Users/nathan/Documents/github/nativescript-stuff/nativescript-cardview/demo/platforms/ios/Pods/MaterialCardView/MaterialCardView/MaterialCardView.swift:125:27: note: add parentheses to silence this warning
    override init!(layer: AnyObject!) {
                          ^
                          (         )
/Users/nathan/Documents/github/nativescript-stuff/nativescript-cardview/demo/platforms/ios/Pods/MaterialCardView/MaterialCardView/MaterialCardView.swift:125:14: error: failable initializer 'init(layer:)' cannot override a non-failable initializer
    override init!(layer: AnyObject!) {
```

**Comment by NathanWalker** [comment]
Appears it may not be compatible with latest Swift:
https://github.com/cemolcay/MaterialCardView/issues/1

May need to help bring that pod up to date :/

**Comment by bradmartin** [comment]
Hey @NathanWalker, I know the bare minimum in regards to iOS and using the cocoapods. @NathanaelA might can provide better feedback to you if you want to take on the iOS version. I think the pod you're using is the only one I've seen that mimics material design so it is the way to go. I just don't know enough iOS to help out. Hence why most of my plugins I nail the android side down and get some help with iOS if needed :) 

At any rate, thanks for helping out and hopefully we can get this done.

**Comment by NathanaelA** [comment]
@NathanWalker my blog post might have the missing piece you need.  http://fluentreports.com/blog/?p=167  -- It walks through both sides of the equation.

**Comment by NathanWalker** [comment]
Absolutely. I'll plan on filling the iOS gap for all your plugins once I figure this out. ;)

@NathanaelA Thank you! I'll check it out.

**Comment by NathanaelA** [comment]
@NathanWalker  Oh, I should also mention; NativeScript does NOT need the cocoapod to be compatible with Swift; it just has to work with ObjectiveC.

**Comment by NathanWalker** [comment]
Great info, thanks. The blog post is definitely answering some questions. I'll post back on progress, may be later this weekend.

**Comment by bradmartin** [comment]
@NathanWalker - any luck on the iOS side?

**Comment by NathanWalker** [comment]
I'm planning on getting back into this later today. I'm likely going to
fork the Pod to fix the Swift errors (issue a PR) and work from that fork
until it gets merged and released.

**Comment by NathanWalker** [comment]
@bradmartin you might have a look here (pull this branch ... need assistance with the custom xml... something i'm missing here), but I forked the iOS pod and fixed it up, so the Podfile references my working fork of that pod:
https://github.com/NathanWalker/nativescript-cardview/tree/ios-support

**Comment by NathanWalker** [comment]
Ok I got past the xml issue, now just to configure the plugin right...

**Comment by mikeres0** [comment]
+1

**Comment by mikeres0** [comment]
@NathanWalker Any update on this man? Eagerly awaiting it's release :+1:

**Comment by NathanWalker** [comment]
I have it working in my fork. There's still some style things to configure like shadowing etc. I've been buried at work but hope to be able to finish it out this week. It is in usable form though and we could potentially merge it and I could submit another PR at week's end with the style stuff hopefully?

**Comment by mikeres0** [comment]
@NathanWalker Whatever you think is best :) No pressure though, I understand how work takes over!

**Comment by bradmartin** [comment]
@NathanWalker - once you get this ready and submitted, I'll send it over to the team to be a verified plugin. Good way to get some nice street cred. Thanks for helping out :+1:

**Comment by klever34** [comment]
@NathanaelA @NathanWalker the nativescript-cardview plugin works only when running on android devices, how do i fix this on iOS?
