### ISSUE TITLE
iOS Build Error on Telerik AppBuilder

### ISSUE THREAD

**Issue by tsaboin** [bradmartin/nativescript-cardview#21]
Hi @bradmartin 

Same issue as https://github.com/bradmartin/nativescript-floatingactionbutton/issues/24

Getting the following error on the Telerik AppBuilder when trying to build a project.

Error: Cannot build project because module nativescript-cardview contains insecure code. Remove the module and try again.

**Comment by tsaboin** [comment]
Do you need to get whilelisted for every plugin or once as an author?

**Comment by bradmartin** [comment]
Once as an author. They said next release

**Comment by bradmartin** [comment]
AppBuilder 3.3 was released on June 9th, I have been whitelisted so there should not be any more issues with plugins I've authored.

**Comment by tsaboin** [comment]
Thanks for @bradmartin However, I have 3.3 since 9th of June and immediately I tried the plugin but still get the same error. Even today, same error.

**Comment by bradmartin** [comment]
Let me contact telerik again. Thanks for letting me know.

**Comment by bradmartin** [comment]
Hi @tsaboin try it now. Found out all maintainers of a plugin have to be white listed. They've white listed those on the card view plugin and tested that it works now. Let me know if you get it working

**Comment by tsaboin** [comment]
Thanks. It worked. Build went fine. However nativescript-floatingactionbutton still not working.
