### ISSUE TITLE
cardview not working in angular 2

### ISSUE THREAD

**Issue by pep108** [bradmartin/nativescript-cardview#24]
I've been trying to get this working with angular 2 and the card will just not render on iOS or android. 

I followed the instructions in #17 and the cardview.ios.js and cardview.android.js files are being executed, but the card is not rendering as it should. This is how the batman demo is rendering...

<img width="375" alt="screen shot 2016-07-06 at 5 56 28 am" src="https://cloud.githubusercontent.com/assets/9968700/16618731/afd5a510-433f-11e6-979f-dd108ba2a70a.png">

Any thoughts?

**Comment by bradmartin** [comment]
I haven't used ng2 but it does work with ng2. You might try joining the
slack channel for NativeScript and asking there because that's where I have
seen devs using it.

**Comment by pep108** [comment]
will do, thanks for the quick response
