### ISSUE TITLE
adding cardview to angular project

### ISSUE THREAD

**Issue by krismcfarlin** [bradmartin/nativescript-cardview#25]
How would I "Make sure you include xmlns:Card="nativescript-cardview" on the Page element" if I am using the "nativescript-angular/router"?

**Comment by bradmartin** [comment]
Hey @krismcfarlin that's non ng2. I should specify that I guess :) I don't use ng2 so I forget these things. With ng2 + NativeScript you'd registerElement(). There should be an example somewhere how to do that with ng2.

**Comment by bradmartin** [comment]
Check the doc on the DrawingPad plugin here: https://github.com/bradmartin/nativescript-drawingpad#angular - the same process for UI plugins with NativeScript+Angular
