### ISSUE TITLE
Error when run on emulator

### ISSUE THREAD

**Issue by bosencoding** [bradmartin/nativescript-cardview#27]
Hi, 
i have tried the demo inside gits file and i have received messages like this,

```
node_modules/nativescript-cardview/index.d.ts(1,15): error TS2306: File '/Users/artemist/Documents/NativeScripts/nativescri
pt-cardview/demo/node_modules/nativescript-cardview/cardview.d.ts' is not a module.

TypeScript compiler failed with exit code 1
```

What does this mean?

**Comment by bradmartin** [comment]
It's a typescript error. I need to fix the definition, my fault. I'll
republish in a couple hours

**Comment by bradmartin** [comment]
@hany-andriyanto I've published a new release that should resolve this issue, can you try it out. If it works, close this issue please. Thanks.

**Comment by bosencoding** [comment]
Brad, it's still error..

```
bash-3.2$ tns livesync android --watch
Executing before-prepare hook from /Users/artemist/Documents/NativeScripts/nativescript-cardview/demo/hooks/before-prepare/
nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
app/main-view-model.ts(15,16): error TS2352: Neither type 'View' nor type 'CardView' is assignable to the other.
  Property 'radius' is missing in type 'View'.

app/main-view-model.ts(16,10): error TS2339: Property 'animate' does not exist on type 'CardView'.

app/main-view-model.ts(21,12): error TS2339: Property 'visibility' does not exist on type 'CardView'.

app/main-view-model.ts(38,16): error TS2352: Neither type 'Observable' nor type 'CardView' is assignable to the other.
  Property 'android' is missing in type 'Observable'.

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).....
```

**Comment by bradmartin** [comment]
Okay, this should be fixed now @hany-andriyanto - I don't get any issues with the demo code (that is what you're running correct?). My compiler passes all checks now. So you should be good, was a TS def issue.

**Comment by jeebee2013** [comment]
hi 
tried with iOS simulator
got this error after Build success
Service exited due to signal: Segmentation fault: 11

any idea ?
thanks

**Comment by bradmartin** [comment]
Usually theres a little more context to a seg fault error. What precedes the seg fault line?

**Comment by bosencoding** [comment]
Following the tips, remove platform and add platform again, and no issues.
My problem has been solved, you can close it.
thanks Brad,
