### ISSUE TITLE
Typescript Error While Registering CardView In NG2 App

### ISSUE THREAD

**Issue by shripalsoni04** [bradmartin/nativescript-cardview#28]
To use CardView in angular 2 app, when we try to register CardView by `registerElement('CardView', () => CardView);`. Typescript compiler gives error: '() => typeof CardView' is not assignable to parameter of type '() => ViewClass'.

The error is due to in definition file extending CardView by ContentView is missing.

So extending CardView by ContentView in definition file will fix this.

```
import { ContentView } from 'ui/content-view';
/**
 * Contains the CardView class, which represents a card view component.
 */

export declare class CardView extends ContentView {
...
}
```

**Comment by bradmartin** [comment]
Forgot that when cleaning up the TS defs last release. Thanks for pointing it out. 
Fixed with 1.1.11
