### ISSUE TITLE
[Android] Image inside CardView gets grayscaled

### ISSUE THREAD

**Issue by roblav96** [bradmartin/nativescript-cardview#32]
## Source

``` xml
<Card:CardView class="card">
    <GridLayout rows="auto" columns="auto,*" class="convos-list-wrapper" tap="{{ onItemTap }}">
        <Image row="0" col="0" imageSource="{{ item.image }}" />
        <StackLayout row="0" col="1" orientation="vertical">
            <Label class="h4" text="{{ item.name }}" />
        </StackLayout>
    </GridLayout>
</Card:CardView>
```
## WITH CardView

![WITH CardView](http://i.imgur.com/MdQQByu.png)
## WITHOUT CardView

![WITH CardView](http://i.imgur.com/trVPFbI.png)
## Info - Core (not ng2)

```
┌──────────────────┬────────────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version            │ Latest version │ Information │
│ nativescript     │ 2.4.0-2016-09-18-6687      │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.3.0                      │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.4.0-next-2016-09-29-1186 │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.4.0-2016-9-28-1          │ 2.3.0          │ Up to date  │
└──────────────────┴────────────────────────────┴────────────────┴─────────────┘
```

Nothing comes up in the `adb logcat` either. I wish there was more info I could provide ya 😞

**Comment by bradmartin** [comment]
Sorry for missing this @roblav96 - this seems related to a bug in 2.3.0 core modules that was messing up the layers and images.

**Comment by roblav96** [comment]
Ye it seems to do with the new image cacheing they integrated. I haven't tried this recently but will.

**Comment by bradmartin** [comment]
@roblav96 just checking if you've tried with 2.4 yet or confirmed it was the bug in 2.3?

**Comment by roblav96** [comment]
@bradmartin I have not but I will test this today and let you know.

**Comment by bradmartin** [comment]
I've used this today with an image inside the cardview and it's not being distorted in any way. Closing for now. If still and issue please let me know. Thanks!

**Comment by roblav96** [comment]
@bradmartin sorry, forgot to check :X
