### ISSUE TITLE
[iOS] Can't find variable: MaterialCard

### ISSUE THREAD

**Issue by manijak** [bradmartin/nativescript-cardview#33]
I just installed 1.2.0 of the plugin (using it for the first time). And I get this error when running the app:

```
myapp.app/app/tns_modules/nativescript-cardview' not found for element 'nativescript-cardview:CardView'.
       ↳Can't find variable: MaterialCard
```

Tried also running via Xcode, but get the same error. Looks similar to: https://github.com/bradmartin/nativescript-cardview/issues/12

Using {N} 2.3.0, xcode 8 on macOS Sierra 10.12, pod version 1.0.1

**Comment by bradmartin** [comment]
@manijak did you ever get this working trying a different version of cocoapods locally or anything?

**Comment by manijak** [comment]
Yeah, sorry about that. I had several pod versions installed. So I removed all of them and installed 0.39.0. Worked after that.
