### ISSUE TITLE
Issues with iOS, build failing

### ISSUE THREAD

**Issue by sudhanshu-15** [bradmartin/nativescript-cardview#36]
I started with card view on Android and it was working perfectly fine, then I had to test for iOS and here things started to get tricky. My code was throwing an error on MaterialCard.swift, so I tried running the demo you have available, and the project was throwing the same error. I also tried to run it on 2 different systems hoping that there was some configuration issue on one of them, but both of my systems were giving the error. I also tried opening the .xcodeproj file and .xcworkspace as per suggestions in the closed issues, but that didn't work either.
Here is the error log:
<pre>
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:13:5: error: expected declaration
    open var cornerRadius: CGFloat = 2
    ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:13:9: error: consecutive declarations on a line must be separated by ';'
    open var cornerRadius: CGFloat = 2
        ^
        ;
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:15:5: error: expected declaration
    open var shadowOffsetWidth: Int = 0
    ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:15:9: error: consecutive declarations on a line must be separated by ';'
    open var shadowOffsetWidth: Int = 0
        ^
        ;
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:16:5: error: expected declaration
    open var shadowOffsetHeight: Int = 2
    ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:16:9: error: consecutive declarations on a line must be separated by ';'
    open var shadowOffsetHeight: Int = 2
        ^
        ;
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:17:5: error: expected declaration
    open var shadowColor: UIColor? = UIColor.black
    ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:17:9: error: consecutive declarations on a line must be separated by ';'
    open var shadowColor: UIColor? = UIColor.black
        ^
        ;
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:18:5: error: expected declaration
    open var shadowOpacity: Float = 0.4
    ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:18:9: error: consecutive declarations on a line must be separated by ';'
    open var shadowOpacity: Float = 0.4
        ^
        ;
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:20:14: error: expected declaration
    override open func layoutSubviews() {
             ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:20:13: error: consecutive declarations on a line must be separated by ';'
    override open func layoutSubviews() {
            ^
            ;
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:20:14: error: expected declaration
    override open func layoutSubviews() {
             ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:20:18: error: consecutive declarations on a line must be separated by ';'
    override open func layoutSubviews() {
                 ^
                 ;
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:20:24: error: overriding instance method must be as accessible as the declaration it overrides
    override open func layoutSubviews() {
                       ^
                  public 
UIKit.UIView:23:17: note: overridden declaration is here
    public func layoutSubviews()
                ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:20:24: error: overriding declaration requires an 'override' keyword
    override open func layoutSubviews() {
                       ^
                  override 
UIKit.UIView:23:17: note: overridden declaration is here
    public func layoutSubviews()
                ^
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:17:38: error: type 'UIColor' has no member 'black'
    open var shadowColor: UIColor? = UIColor.black
                                     ^~~~~~~ ~~~~~
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:26:40: error: value of type 'UIColor' has no member 'cgColor'
        layer.shadowColor = shadowColor?.cgColor
                            ~~~~~~~~~~~^ ~~~~~~~
/Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift:29:28: error: value of type 'UIBezierPath' has no member 'cgPath'
        layer.shadowPath = shadowPath.cgPath
                           ^~~~~~~~~~ ~~~~~~

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/sudhanshu/Downloads/nativescript-cardview-master/demo/platforms/ios/Pods/MaterialCard/MaterialCard/Classes/MaterialCard.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
Command xcodebuild failed with exit code 65
</pre>

Please help me.

**Comment by bradmartin** [comment]
@NathanWalker - does any of the above mean anything to you?

**Comment by NathanWalker** [comment]
@sudhanshu-15 Need some info to help here:
1. What version of XCode do you have installed?
2. version of NativeScript?
3. CocoaPods version?

**Comment by sudhanshu-15** [comment]
@NathanWalker 

XCode 7.3 on one machine, Xcode 7.1 on the other
NativeScript 2.3.0
CocoaPods 1.0.1

**Comment by NathanWalker** [comment]
Ah ok that makes sense. With that combo you _very_ likely need to downgrade to CocoaPods `0.39.0`, you can follow this article for how to do that: 
http://diego.org/2015/09/24/downgrading-cocoapods/

You can alternatively upgrade XCode to 8.1 and upgrade CocoaPods to `1.1.1`.

**Comment by sudhanshu-15** [comment]
I did try downgrading to Cocoapods `0.39.0` and it was giving the same error, will try upgrading though and keep you posted. Thanks a lot for looking into this :)

**Comment by NathanWalker** [comment]
Cocoapods can be frustrating, they really can. Sometimes getting the versions right is tricky... there's also `cocoapods-core` that you have to downgrade too (this is often left same).

At any rate, XCode 8.1 improved some Swift handling especially regarding 3.0 which `MaterialCard` uses.

**Comment by NathanWalker** [comment]
Also update to {N} 2.4.0 which landed today by following this:
http://fluentreports.com/blog/?p=419

Let us know.

**Comment by sudhanshu-15** [comment]
I completely removed cocoapods and installed 0.39.0. Upgrading Xcode now and will upgrade {N} too. Thanks :)

**Comment by NathanWalker** [comment]
Crossing fingers it works!  It's working here so it should!

**Comment by NathanaelA** [comment]
@NathanWalker @sudhanshu-15 - I'm going to chime in here just on CocoaPod. 

 CocoaPod less than 1.0.0 does NOT work anymore.  The site that serves the pod's will refuse any CocoaPods requests < 1.0 so you are NOW REQUIRED to be using 1.0 as of this last Saturday.

So If you are using 0.39, and you have all the pods already installed you are fine, but the next time you go to download a POD file, 0.39 will fail.

**Comment by NathanWalker** [comment]
Thanks for clarification @NathanaelA 👍

**Comment by sudhanshu-15** [comment]
@NathanWalker @NathanaelA UPDATE: Installed XCode 8.1, Nativescript 2.4.0 and Cocoapods 1.1.1. Errors gone and to build the app, but the launch screen is not being created. Trying to debug. Will post update when it is done. 👍

**Comment by NathanWalker** [comment]
@sudhanshu-15 great news :) So on the launch screen, you likely need to update your project to new format. Try this:

```
tns create test-project 
```

Then open that fresh project and copy the `app/App_Resources/iOS` into your project, it's a new format.

**Comment by sudhanshu-15** [comment]
@NathanWalker Thanks for the update, I tried that and the same issue.
![image](https://cloud.githubusercontent.com/assets/883233/20377680/3834fc5c-ac5f-11e6-9e0f-e7f77a8f7dcc.png)
Screen freezes after the splash screen.
Working fine on Android.

**Comment by sudhanshu-15** [comment]
@NathanWalker UPDATE: Opened .xcworkspace file on XCode and I was able to launch the application.

![image](https://cloud.githubusercontent.com/assets/883233/20377996/5105109e-ac61-11e6-8963-7a7ec19b8535.png)

But when I tried to run with VS Code debugger, it froze again at the splash screen.

**Comment by bradmartin** [comment]
I've had success running the plugin with NS 2.4 and Xcode 8.1. I'm going to close this for now, if still an issue please let us know. Thanks.
