### ISSUE TITLE
Investigate shadowOffset with latest changes for iOS

### ISSUE THREAD

**Issue by NathanWalker** [bradmartin/nativescript-cardview#40]
@manijak I would like to release a new version with your integrated changes, however investigating today presented some trouble. I can't get the shadowOffset to change. Currently your implementation ends up with the shadow always being cast upwards? See screenshot.
The default state should probably be with a subtle shadow cast 1-2 points to the right and down (definitely not upwards I don't think).

Could you investigate this and push any changes to a PR to fix?
Then we can get a new version out with this. Thanks again.

<img width="377" alt="screen shot 2017-01-07 at 1 03 16 pm" src="https://cloud.githubusercontent.com/assets/457187/21745166/e938b73a-d4d9-11e6-9db0-a24b410b4dff.png">

**Comment by manijak** [comment]
@NathanWalker sorry for the late reply, just came back from my vacation. 

Yeah, it seems that I messed up the default values for shadowOffset in the .ios.ts file. We just need to add proper values here and it should work.

**Comment by manijak** [comment]
@NathanWalker Created a new PR for this https://github.com/bradmartin/nativescript-cardview/pull/43

**Comment by bradmartin** [comment]
1.3.0 published.
