### ISSUE TITLE
shadow direction android

### ISSUE THREAD

**Issue by ezequielzacca** [bradmartin/nativescript-cardview#50]
is there any way to set the direction of the shadow for android? i want to make a bottom navigation panel but the shadow always goes to bottom so i cant get shadow on top of the menu

**Comment by bradmartin** [comment]
Don't think so. Would have to look at the android APIs for the cardview but
from memory I don't think android has anything for this. Of course I could
be wrong :) will have to look later.

**Comment by bradmartin** [comment]
Hi @ezequielzacca - no provided way to do what you're trying from the native control. The cardview doc here - https://developer.android.com/reference/android/support/v7/widget/CardView.html lists all that is possible.
