### ISSUE TITLE
CardView doesn't refresh

### ISSUE THREAD

**Issue by ownleviathan** [bradmartin/nativescript-cardview#53]
Hello,
After updating my app to nativescript 3.0 and also update your plugin, now my app my CardView doesn't refresh. 
For example, when I load for the first time is not showing the values, but when I refresh the page, now the data is coming. 
To see a new data, always I have to refresh, is not upgrading the data immediately.

This is the code:

///xml page/////
<StackLayout
        xmlns="http://www.nativescript.org/tns.xsd"
        xmlns:gv="nativescript-grid-view"
        xmlns:Card="nativescript-cardview">
    <label text="step 1"/>
    <GridLayout id="kpiCardsGridLayoutOTS" row="1">
        <gv:GridView id="_listViewKPICardsOTS" backgroundColor="#f6f6f6" items="{{ _kpiCards }}" colWidth="{{ screenWidthsCol }}" rowHeight="85">
            <gv:GridView.itemTemplate>
                <StackLayout>
                    <Card:CardView  class="cardStyle" tap="navigateOnCardClick">
                        <GridLayout rows ="*, *" columns="auto,*" stretch="aspectFill" >
                            <label fontSize="12" id="key" colSpan="4" text="{{ key }}"  margin="5 5 0 5" textWrap="true" className="alright" row="1" col="0" color="black" />
                            <Label   row="0" col="0" colSpan="1" margin="0 5 5 5" text="&#xf062;" className="font-awesome" color="green"   visibility="{{ vShowArrow == 'up'  ? 'visible' : 'collapsed' }}" />
                            <Label   row="0" col="0"  text="&#xf063;" className="font-awesome" color="red"  visibility="{{ vShowArrow == 'down' &&  key != 'Daily Tracker WTD Target To Go' ? 'visible' : 'collapsed' }}" />
                            <label fontSize="18" colSpan="4" margin="0 5 5 0" text="{{ vPercent }}" className="alright" textWrap="true" row="0"  col="1" color="#049FD9"/>
                        </GridLayout>
                    </Card:CardView>
                 </StackLayout>
            </gv:GridView.itemTemplate>
        </gv:GridView>
    </GridLayout>
</StackLayout>

************** Package .json ********

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.xxx.mbrxx",
    "tns-ios": {
      "version": "3.0.0"
    },
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/platform-browser": "^4.1.1",
    "@angular/router": "^4.1.1",
    "base-64": "^0.1.0",
    "nativescript-angular": "^3.0.0",
    "nativescript-cardview": "^2.0.0-rc.0",
    "nativescript-collapsing-header": "2.0.0",
    "nativescript-exit": "^1.0.0",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-fingerprint-auth": "4.0.0",
    "nativescript-floatingactionbutton": "3.0.0",
    "nativescript-grid-view": "3.0.0",
    "nativescript-intl": "3.0.0",
    "nativescript-loading-indicator": "2.3.2",
    "nativescript-master-technology": "^1.1.0",
    "nativescript-oauth": "file:../nativescript-oauth",
    "nativescript-statusbar": "1.0.0",
    "nativescript-telerik-ui": "2.0.1",
    "rxjs": "^5.4.0",
    "tns-core-modules": "^3.0.0",
    "utf8": "^2.1.2",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "babel-traverse": "^6.22.1",
    "babel-types": "^6.22.0",
    "babylon": "^6.15.0",
    "filewalker": "^0.1.3",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.4.4",
    "tns-platform-declarations": "^3.0.0",
    "typescript": "^2.3.2"
  }
}

**Comment by bradmartin** [comment]
Sorry for the trouble, could you add some more context to the issue. I'm not really sure what 'should' be happening in your app with the details so far 😄 be glad to help but I'll need more info to get the full picture. Thanks.
