### ISSUE TITLE
default style issues

### ISSUE THREAD

**Issue by jdnichollsc** [bradmartin/nativescript-cardview#55]
Hi guys, testing on iOS with the last version of NativeScript: 
<img width="376" alt="captura de pantalla 2017-06-01 a la s 12 10 33 a m" src="https://cloud.githubusercontent.com/assets/2154886/26665434/39ab512c-465f-11e7-8577-e9e3ffa0d13f.png">

Let me know what you think, Nicholls

**Comment by bradmartin** [comment]
Can you try the latest release and see if the issue still exists? Also, can you provide your markup for the screenshot above?

**Comment by jdnichollsc** [comment]
@bradmartin hi man, thanks for the quickly response! check the code please: https://github.com/proyecto26/NativeScript/blob/master/src/app/item/items.component.html

The height was fixed using `height="100%"`
Let me know what you think, thanks again! 👍
