### ISSUE TITLE
no styles when in a scrollView

### ISSUE THREAD

**Issue by ButterMeWaffle** [bradmartin/nativescript-cardview#56]
As the title says, you wont get the styles of the CardView element when placed inside of a scrollView.

Only confirmed for angular4 builds.

**Comment by bradmartin** [comment]
@SamuelGRwebfab - did you ever see if this was fixed with core?

**Comment by ButterMeWaffle** [comment]
I did not, we decided not to use the cardview style in the app so I am no longer using the plugin.
