### ISSUE TITLE
using css class parameter breaks iOS when navigating

### ISSUE THREAD

**Issue by johnnyzen** [bradmartin/nativescript-cardview#58]
Hi there

Using nativescript 3.0.2 & Angular/Typescript

Using the following in a html layout breaks iOS when navigating to the View. (The navigation doesnt do anything. The app doesnt crash)

`this.routerExtensions.navigate(['/main']);`

This doesnt work:

`<CardView class="cardStyle" elevation="4" radius="1" marginBottom="2" width="100%">
            <StackLayout orientation="vertical" padding="20">
            </StackLayout>
</CardView>`

This works:

`<CardView elevation="4" radius="1" marginBottom="2" width="100%">
            <StackLayout orientation="vertical" padding="20">
            </StackLayout>
</CardView>`

`.cardStyle {
    background-color: #ffffff;
}`

Everything works in Android as expected.

**Comment by johnnyzen** [comment]
An update:

If I remove from the css
`background-color: #ffffff;`

It works, so it seems there is a problem specifying this property? Any ideas what might be causing this?

**Comment by bradmartin** [comment]
Not sure. @manijak - do you have any idea what might be happening here on iOS?

**Comment by manijak** [comment]
This is unknown to me. Every single of my `CardView` instances have a `class` applied, and they work just fine both on iOS and Android. Could be an ng2 only issue, I use vanilla js for my apps.

**Comment by bradmartin** [comment]
Yea might be something with angular instance. Prob need to check with the
angular repo to see if they have any idea.

**Comment by manijak** [comment]
Ups, spoke too soon. Just upgraded the plugin to latest version and get the same issue. Using `background-color` css element makes the app crash when navigating back to a view that has CardView with that css-element. Weird error. 

Using `backgroundColor="white"` directly on the XML, works fine.

**Comment by manijak** [comment]
@bradmartin  It appears to be going down when it hits line 37 in ios.js
```javascript
CardView.prototype[cardview_common_1.backgroundInternalProperty.setNative] = function (value) {
        this.nativeView.backgroundColor = new color_1.Color(value.color + "").ios;
};
```
Commenting out this entire property, makes the issue go away. I do not understand what this property does, since there already is a `backgroundColorProperty` just above this one, and it does the job. 

But after a few tests I did also had to add a `if(value)` check before line 34, since the `value` was still sometimes `undefined`. I think this is when CardView is located innside a Repeater.

**Comment by bradmartin** [comment]
I've seen an issue on another plugin similar to this. Works with XML not
css and causes issues. don't recall which plugin. Maybe pull to refresh or
radio button. I'll have to look later. However I prob won't be able to dig
too deep until late in the week or next.

**Comment by johnnyzen** [comment]
Thanks guys for looking into 👍
