### ISSUE TITLE
In listview cell selection problem

### ISSUE THREAD

**Issue by oncul** [bradmartin/nativescript-cardview#59]
Hello, cardview in listview. when i press the item, cardview background, radius and shadow disappering. Do you have a solution for this?

**Comment by bradmartin** [comment]
Not at the moment, could you please provide a video or .gif showing this in effect? Also providing your markup for the listview and any css that applies to this as well so I can try a demo of it later and see if I can find a solution. [here](http://www.cockos.com/licecap/) is a free tool for recording .gifs that are great to drop on github issues. That would help to see what you're seeing 😄 and a fix is definitely possible.

Also is this on iOS? If so, I might have an idea what's happening. Thanks.

**Comment by oncul** [comment]
Yes, it happened on ios. i will send a screenrecord about the problem.

**Comment by oncul** [comment]
![untitled](https://user-images.githubusercontent.com/370796/27510221-e75c9a20-5914-11e7-83ba-48f3ea086f47.gif)

**Comment by bradmartin** [comment]
Yep. You need to adjust the iOS listview. I'm not near comp now or I'd
paste snippet but basically that's the iOS listview selection over taking
the cell. I'm not certain but I'm sure the card can be on top of the cell
always even during selection but not my area (iOS) so I'll look around
later. However for now you prob can adjust the selection coloring event on
iOS. I'll provide code for it later.

**Comment by bradmartin** [comment]
@manijak @NathanWalker - is there something on iOS to make the card view not do this on the listview selection?

**Comment by bradmartin** [comment]
@cagatayoncul snippet below should disable the iOS list selection that you see currently. I'm not well versed with iOS behavior/design so I can't answer if this is best long term but it should prevent the card from disappearing on selection. This is on the ListView's `itemLoading` event.

``` typescript
    /**
     * onItemLoading event for the listview items
     */
    public onItemLoading(args: ItemEventData) {
        /// just disabling the iOS item selection highlighting
        if (isIOS) {
            const cell = args.ios
            if (cell) {
                cell.selectionStyle = UITableViewCellSelectionStyleNone
            }
        }
    }
```

**Comment by oncul** [comment]
Thank you, if i found a better solution, i will post ;)

**Comment by manijak** [comment]
Yeah it should work, I use it the same way.
```javascript
exports.listViewItemLoading = function(args) {
    if (frameModule.topmost().ios) {
        var cell = args.ios;
        cell.selectionStyle = UITableViewCellSelectionStyle.UITableViewCellSelectionStyleNone;
        cell.backgroundColor = new colorModule.Color("transparent").ios;
    }
}
```
