### ISSUE TITLE
angular version

### ISSUE THREAD

**Issue by nelsonwilliam11** [bradmartin/nativescript-cardview#60]
is there angular version for this repo

**Comment by bradmartin** [comment]
of the repo? no. The plugin works with angular tho... https://github.com/bradmartin/nativescript-cardview#angular-nativescript

**Comment by nelsonwilliam11** [comment]
Sorrry I wrote the word repo mistakenly
Anyways thanks

**Comment by bradmartin** [comment]
:) typos get us all :) if you have any questions let me know
