### ISSUE TITLE
TypeError: Cannot read property 'newDrawable' of null

### ISSUE THREAD

**Issue by ivanwitzke** [bradmartin/nativescript-cardview#64]
Anytime I add a `<CardView></CardView>` to anywhere in my app, I get the following error:

```bash
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateViewHolder failed

TypeError: Cannot read property 'newDrawable' of null
File: "file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js, line: 389, column: 53

StackTrace: 
	Frame: function:'View.(anonymous function)', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 389, column: 54
	Frame: function:'applyAllNativeSetters', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 964, column: 95
	Frame: function:'initNativeView', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 894, column: 9
	Frame: function:'ViewBase.onResumeNativeUpdates', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 671, column: 22
	Frame: function:'ViewBase._resumeNativeUpdates', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 237, column: 18
	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 215, column: 14
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 62, column: 35
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 471, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 446, column: 14
	Frame: function:'LayoutBaseCommon.insertChild', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 49, column: 14
	Frame: function:'ViewUtil.insertChild', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/nativescript-angular/view-util.js', line: 46, column: 24
	Frame: function:'NativeScriptRenderer.insertBefore', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/nativescript-angular/renderer.js', line: 78, column: 27
	Frame: function:'DebugRenderer2.insertBefore', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13343, column: 23
	Frame: function:'execRenderNodeAction', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9086, column: 22
	Frame: function:'visitRenderNode', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9057, column: 13
	Frame: function:'visitSiblingRenderNodes', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 8988, column: 13
	Frame: function:'visitRootRenderNodes', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 8972, column: 5
	Frame: function:'renderAttachEmbeddedView', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9786, column: 5
	Frame: function:'attachEmbeddedView', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9666, column: 5
	Frame: function:'ViewContainerRef_.insert', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 10133, column: 9
	Frame: function:'ViewContainerRef_.createEmbeddedView', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 10104, column: 14
	Frame: function:'RadListViewComponent._listView.itemViewLoader', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/nativescript-telerik-ui/listview/angular/listview-directives.js', line: 40, column: 55
	Frame: function:'RadListView.getViewForViewType', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/nativescript-telerik-ui/listview/listview-common.js', line: 412, column: 28
	Frame: function:'ListViewAdapter.onCreateViewHolder', file:'file:///data/data/org.nativescript.PizzaApp/files/app/tns_modules/nativescript-telerik-ui/listview/listview.js', line: 64, column: 33


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
	at com.tns.Runtime.callJSMethod(Runtime.java:912)
	at com.tns.Runtime.callJSMethod(Runtime.java:896)
	at com.tns.Runtime.callJSMethod(Runtime.java:888)
	at com.tns.gen.com.telerik.widget.list.ListViewAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.onCreateViewHolder(com.telerik.widget.list.ListViewAdapter.java)
	at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:459)
	at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:20)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
	at com.telerik.widget.list.RadListView.onMeasure(RadListView.java:570)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19883)
	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
	at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:83)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19883)
	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
	at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1059)
	at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:869)
	at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:279)
	at android.view.View.measure(View.java:19883)
	at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
	at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2293)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1384)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1637)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```
Using:
`{N} + Angular(~3.0.0) `
`tns-android 3.1.1`
` tns --version: 3.1.3`

**Comment by bradmartin** [comment]
Did you registerElement as outlined here https://github.com/bradmartin/nativescript-cardview/blob/master/README.md#angular-nativescript ? That might be your issue

**Comment by ivanwitzke** [comment]
Slightly different from the example, but yes...

```typescript
import { registerElement } from 'nativescript-angular/element-registry';
registerElement("CardView", () => require("nativescript-cardview").CardView);
```

**Comment by noordw** [comment]
Yes I am getting the same on Android only

**Comment by jibon57** [comment]
Yes, I am facing same problem with webpack. But without webpack it just fine. @bradmartin Will you please check it with webpack? 

```
JS: ERROR TypeError: Cannot read property 'newDrawable' of null
Running webpack for android...
```

**Comment by noordw** [comment]
I'm Thinking it might be related to 

https://github.com/NativeScript/NativeScript/pull/4633
which is also similar to the issue with background-colour on IOS
#58 using css class parameter breaks iOS when navigating

**Comment by SP1966** [comment]
I believe that the same issue is affecting nativescript-floatingactionbutton:
https://github.com/bradmartin/nativescript-floatingactionbutton/issues/57

In both cases, cardview and floatingactionbutton if the background-color is set in CSS the app crashes. Remove the CSS and all is well, except the background-color is wrong! :)

**Comment by jibon57** [comment]
@SP1966 @noordw but if you try with webpack, you will see it won't work.

**Comment by noordw** [comment]
Just tested you are right, get rid of backgroundColour and it works. At least that lets me keep working until someone figures it out.

Thanks

**Comment by smarza** [comment]
Removing the backgroundColour worked for me too.

In my tests:

- IOS worked with backgroundColour.
- Android only worked without backgroundColour.

So, I created separated html files for both platforms. For now everything is fine.

Thanks guys.

**Comment by bradmartin** [comment]
Anyone care to share their package.json? Also this seems like a recent issue since cardview hasn't been updated in awhile.

**Comment by noordw** [comment]
It is new, Mine broke updating to 3.x

{
  "description": "Xxxxxx",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "Trinoor Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.trinoor.TASeA",
    "tns-android": {
      "version": "3.1.1"
    },
    "tns-ios": {
      "version": "3.2.0-2017-7-28-1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.5",
    "@angular/common": "~4.2.5",
    "@angular/compiler": "~4.2.5",
    "@angular/core": "~4.2.5",
    "@angular/forms": "~4.2.5",
    "@angular/http": "~4.2.5",
    "@angular/platform-browser": "~4.2.5",
    "@angular/platform-browser-dynamic": "~4.2.5",
    "@angular/router": "~4.2.5",
    "@angular/upgrade": "~4.2.5",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.0.2",
    "@ngrx/store": "^4.0.2",
    "lodash": "^4.17.4",
    "nativescript-angular": "^4.3.0-2017-8-10-8",
    "nativescript-barcodescanner": "^2.6.1",
    "nativescript-cardview": "^2.0.2",
    "nativescript-checkbox": "^2.1.11",
    "nativescript-exit": "^1.0.1",
    "nativescript-feedback": "^1.0.6",
    "nativescript-i18n": "^0.2.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-ngx-fonticon": "^2.2.3-master-12",
    "nativescript-sqlite": "^1.1.7",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-themes": "^1.1.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.4.2",
    "tns-core-modules": "^3.1.1",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.5.0",
    "typescript": "^2.4.2"
  },
  "nativescript-i18n": {
    "customLangPath": "app/resources/i18n"
  }
}

**Comment by smarza** [comment]
@bradmartin 

```
...
    "tns-ios": {
      "version": "3.2.0-2017-7-5-5"
    },
    "tns-android": {
      "version": "3.2.0-2017-8-10-1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.3.2",
    "@angular/common": "~4.3.2",
    "@angular/compiler": "~4.3.2",
    "@angular/core": "~4.3.2",
    "@angular/forms": "~4.3.2",
    "@angular/http": "~4.3.2",
    "@angular/platform-browser": "~4.3.2",
    "@angular/router": "~4.3.2",
    "angular2-uuid": "^1.1.1",
    "nativescript-angular": "next",
    "nativescript-appversion": "^1.4.1",
    "nativescript-audio": "^3.5.0",
    "nativescript-cardview": "^2.0.2",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-plugin-firebase": "4.0.3",
    "nativescript-pulltorefresh": "^2.0.2",
    "nativescript-ripple": "^2.0.0",
    "nativescript-social-share": "^1.3.2",
    "nativescript-telerik-ui": "^3.0.4",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-zip": "^1.3.2",
    "ngx-pipes": "^1.6.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "^3.0.1",
    "zone.js": "~0.8.16"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.3.2",
    "@ngtools/webpack": "^1.4.1",
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "^4.0.1",
    "extract-text-webpack-plugin": "^2.1.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "^0.26.1",
    "nativescript-dev-typescript": "~0.4.0",
    "nativescript-dev-webpack": "^0.6.3",
    "raw-loader": "^0.5.1",
    "resolve-url-loader": "^2.0.3",
    "typescript": "~2.3.4",
    "webpack": "^3.0.0",
    "webpack-sources": "^1.0.1"
  },
...
```

**Comment by noordw** [comment]
Fixed by
import { NativeScriptI18nModule } from "nativescript-i18n/angular"
to
require("nativescript-i18n");
and removing from imports

**Comment by SP1966** [comment]
Here is my package.json:


  "nativescript": {
    "id": "org.nativescript.PPM",
    "tns-android": {
      "version": "3.1.1"
    },
    "tns-ios": {
      "version": "3.1.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.3",
    "@angular/common": "~4.2.3",
    "@angular/compiler": "~4.2.3",
    "@angular/core": "~4.2.3",
    "@angular/forms": "~4.2.3",
    "@angular/http": "~4.2.3",
    "@angular/platform-browser": "~4.2.3",
    "@angular/router": "~4.2.3",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.0.2",
    "@ngrx/store": "^4.0.2",
    "nativescript-angular": "^4.2.0",
    "nativescript-camera": "^3.0.1",
    "nativescript-cardview": "^2.0.2",
    "nativescript-drop-down": "^3.1.1",
    "nativescript-floatingactionbutton": "^3.0.1",
    "nativescript-gradient": "^2.0.0",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ngx-fonticon": "^2.2.3",
    "nativescript-telerik-ui": "3.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^5.4.0",
    "tns-core-modules": "^3.1.1",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "husky": "^0.14.3",
    "lazy": "1.0.11",
    "lint-staged": "^4.0.1",
    "nativescript-dev-sass": "^1.1.1",
    "nativescript-dev-typescript": "~0.4.5",
    "prettier": "^1.5.2",
    "typescript": "~2.2.1"
  },
  "scripts": {
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "*.ts": ["prettier --write", "git add"]
  },

**Comment by bradmartin** [comment]
Anyone not using angular have this issue? I don't think this plugin has
been updated in a while so we might want to ping this on the nativescript
repo and have the team look at it. I haven't used webpack with NS so it's
not an area I can provide much insight about. I know the styler stuff went
through a bumpy ride during the 3x breaking changes in the core but we
smoothed those out with most plugins so this seems to be something new that
started recently, is that correct? If so will someone create an issue on
the core repo and CC me on it linking here. Curious what is causing the
issue for you all but I haven't seen this personally so that's positive I
guess :)

**Comment by jibon57** [comment]
@bradmartin by removing background-color CSS property also solved webpack issue :)

**Comment by davorpeic** [comment]
Hey @bradmartin I will post here as the topic is more active, but I have issues with fab. But in my case it is funny as I experience this issue only when I run the app from one machine of my colleague, if I run it on mine then I see the button both in simulator (android 7) and on test device (android 6), if he runs the app on the same device then we get this error related with background-color. 

The app is the same and node_modules have same versions, so my assumption is that it could be related with maybe some difference in android sdk packages used to build, I will do further comparison later to try to find out what is different and if issue get fixed

**Comment by bradmartin** [comment]
Sounds good, thanks @davorpeic I have both UI components inside apps using the latest versions of NS and the plugins. So it does seem build related. Keep us posted 👍

**Comment by manijak** [comment]
I am running vanilla TNS 3.1.3 with JS, and also get this issue. I don't get a stacktrace like others, just a white screen with the text: `cannot read property newDrawable of null, undefined`

Highest android sdk version I have is 25 (7.1.1).

**Comment by davorpeic** [comment]
Ok, so I think I found the source of getting my error for FAB. The only difference my app had compared to other pc was in `tns-core-modules`, after doing `npm update` I got the same error as Manijak.

Reverting to `"tns-core-modules": "3.1.0",` fixed the issue with `backgroundColor="red"` on my FAB button. I see that they did some update in relation to background color,not sure if this could be issue.

**Comment by SP1966** [comment]
@davorpeic 

I switched tns-core-modules to 3.1.0 from 3.1.1 and I'm still getting the error. This stuff is way over my head!

**Comment by bradmartin** [comment]
Did you remove and add the platform after changing the core modules?

**Comment by SP1966** [comment]
Yes. In fact I also dropped back from nativescript-angular 4.2.0 to 3.1.3 alternately and that wasn't it either.

**Comment by bradmartin** [comment]
https://github.com/NativeScript/NativeScript/issues/4728#issuecomment-324332545

**Comment by SP1966** [comment]
@bradmartin What does it feel like being a rockstar? Us plebes would like to know!

**Comment by bradmartin** [comment]
Hardly the case :) I'm a code thief drifting thru this life

**Comment by shiv19** [comment]
Facing the same problem on vanilla nativescript

**Comment by deepak4u2006** [comment]
Still removing background-Color from css is working in Android

**Comment by bradmartin** [comment]
The master core modules has the fix. It should ship with 3.2

**Comment by mrkorsar** [comment]
What I must do to get 3.2 ? I tried the command "tns update" and this didn't help

**Comment by bradmartin** [comment]
3.2 isn't released yet if update cmd didn't install it. You can use @next
release I think if you want to try it before official release.

**Comment by bradmartin** [comment]
I've updated the demo to 3.2.0 and all works fine in the demo. Is there a use case that still throws an error for anyone?
