### ISSUE TITLE
Setting radius doesn't have any effect

### ISSUE THREAD

**Issue by fadiallos** [bradmartin/nativescript-cardview#68]
![cardview](https://user-images.githubusercontent.com/31819512/30272629-839872ca-9749-11e7-8d74-fccaac090c1c.png)
Adding a radius property does not change the radius of the cards.

Am I doing something wrong?

**Comment by bradmartin** [comment]
Possibly 😄 I don't see a radius on the `CardView`, only elevation, margin, and a class and don't see the details of the CSS class here 😄. Also, you should put quotes around the property values so the parser doesn't have any trip ups. Looks like you're missing quotes around the margin and elevation on the `CardView`.

**Comment by fadiallos** [comment]
Sorry probably a bad picture to send to show what I mean. 

Class={{item.brand}} puts a background image on the grid. It seems that this image stops the cardview from applying its radius. Not sure why.
The way i got around this was to apply a radius on the gridlayout.
Is there a conflict between radius on cardview and background image on child gridlayout?

Thanks for the quotation tip. I get lazy at times. I'll change them.

**Comment by bradmartin** [comment]
Yea, as far as I know, `radius` still works on the cardview so you might have some conflict with the current layout you have. Also, another tip, you don't need the parent StackLayout on the cardview 👍 - it's a layout itself so you shouldn't need it in this case (from your image).

**Comment by fadiallos** [comment]
Tried removing stacklayout yesterday with unfavourable results. Will have another look at doing it tonight. Without stacklayout it simply presently the last item on the page.

**Comment by bradmartin** [comment]
sometimes, depending on the platform you might need to be explicit with height/width for it to work perfectly, but cardview extends the `ContentView` class which gives it layout container behavior. So yea it'll depend on what you're after but if you can dump that parent, then of course, that's a good thing. Not gonna be a huge deal breaker for what you seem to be trying to do though 😄

**Comment by bradmartin** [comment]
Confirmed radius works, updated demo. Please check the demo if you need to see it in action. Thanks 😄
