### ISSUE TITLE
Cannot read property "newDrawable" of null, undefine

### ISSUE THREAD

**Issue by NikicaAsanin** [bradmartin/nativescript-cardview#71]
My tns version - 3.3.0 
iOS work perfectly but having problem with android device emulator, on app start I get screen with text "Cannot read property "newDrawable" of null, undefine" but I dont have any error in console only on device screen, any idea why?
<img width="969" alt="screen shot 2017-11-08 at 9 18 55 pm" src="https://user-images.githubusercontent.com/5645255/32572321-7865e618-c4ca-11e7-9f46-5d7288890645.png">

**Comment by bradmartin** [comment]
Not sure. Can you provide your markup you are using? The cardview shouldn't be calling any drawables on android, so this makes me think you have an image somewhere that is invalid but seeing your markup would help.

**Comment by imikemiller** [comment]
I have the same error with the following markup

```html
<TabView selectedIndex="0"  (selectedIndexChange)="onIndexChanged($event)" sdkExampleTitle sdkToggleNavButton class="icon">
    <StackLayout *tabItem="{iconSource: '~/images/home.png'}">
        <CardView class="cardStyle" margin="10" elevation="40" radius="1" >
            <GridLayout rows="10,30,30,250, auto, auto,10" columns="10,40, *, 30,10">
                <Label horizontalAlignment="left" [text]="Home" textWrap="true" col="1" row="5" colSpan="3"></Label>
            </GridLayout>
        </CardView>
    </StackLayout>
    <StackLayout *tabItem="{iconSource:'~/images/cards.png'}">
        <Label text="Cards" textWrap="true" class="h2 m-x-auto" color="blue"></Label>
    </StackLayout>
    <StackLayout *tabItem="{iconSource:'~/images/settings.png'}">
        <Label text="Settings" textWrap="true" class="h2 m-x-auto" color="blue"></Label>
    </StackLayout>
</TabView>

**Comment by imikemiller** [comment]
https://github.com/bradmartin/nativescript-cardview/issues/64

This fixed it for me. Specifically had to change the version of `"tns-core-modules":"^3.3.0"` in package.json and then run `tns update`
