### ISSUE TITLE
bug on IOS only. Android looks perfect

### ISSUE THREAD

**Issue by pzdunek** [bradmartin/nativescript-cardview#72]
Project successfully prepared (iOS)
Executing after-prepare hook from /Users/piotrz/Projekty/ITR/itr-medandlife-energetyka-mobile/Med and Life/hooks/after-prepare/nativescript-dev-sass.js
Successfully transferred login.component.html.
Refreshing application...
Successfully synced application org.nativescript.MedandLife on device 76D91E5B-D795-4669-9EB5-573BEDAD6E6A.
1   0x10624fbc8 -[TNSRuntime executeModule:referredBy:]
2   0x105cf1c71 main
3   0x10bbe5d81 start
undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')

**Comment by pzdunek** [comment]
any hints?

**Comment by bradmartin** [comment]
Missed this previously. Have you tried rebuilding the app? Also can you provide some screenshots of what is different?

**Comment by bradmartin** [comment]
Let me know if still any issue lingering here. Thanks 😄
