### ISSUE TITLE
ios display issue

### ISSUE THREAD

**Issue by glen-stephens** [bradmartin/nativescript-cardview#74]
Love the plugin!  Only buggy thing is on ios, when drawn in a listview, tapping on the card view treats the card as transparent on ios, even though a background color is explicitly set.  Android does not exhibit this behavior.  See example image:

![cardview](https://user-images.githubusercontent.com/32279761/33637406-06a3b072-d9de-11e7-8049-62a6cf987d7b.png)

**Comment by bradmartin** [comment]
Without looking I suspect it's the listview selection behavior of iOS
uitableview. You'll want to disable the selection behavior. I can provide
the snippet later. Not near computer now.

**Comment by glen-stephens** [comment]
Thanks!! Here is what I get if I give my labels a background color, however it would be better to get the card's background color to work.

![card2](https://user-images.githubusercontent.com/32279761/33639369-2f703764-d9e8-11e7-8b46-90e24f97e473.png)

**Comment by sittingbool** [comment]
having the same issue outside of listview too. also in earlier versions. if you wrap the content in a layout (I used Gridlayout) and give that a background color it works. Otherwise all the views inside the card will have a shadow. only on iOS

**Comment by yoat** [comment]
I have my CardViews wrapped in a WrapLayout with an explicit background color and still had the text-shadow issue on iOS.

`<ScrollView>
    <WrapLayout orientation="horizontal" background="#f5f5ed">
        <CardView class="cardStyle" margin="10" elevation="40" radius="25">
            <GridLayout rows="10, auto, 10, auto, 10, auto, 10" columns="10, * ,10">
                <Label text="Quick Links" class="h2 text-center" col="1" row="1" textWrap="true"></Label>
                <Button text="View" class="purchase-button" (tap)="goBrowse()" col="1" row="3"></Button>
                <Button text="Visit" class="purchase-button" (tap)="purchaseSubscription()" col="1" row="5"></Button>
            </GridLayout>
        </CardView>`

Is that what @sittingbool is describing? Any suggestions (maybe a different layout or something)?

I'm using Angular with NativeScript and everything looks as expected on Android.

**Comment by MichaelMarner** [comment]
Here's a workaround if you are running into this trying to have `CardView` inside a `ListView`. Assuming Angular, use an `ElementRef` to access the `ListView` inside your component, and then disable `allowsSelection`. eg:

`Component.ts`
```
export class MyComponent {
  @ViewChild('list') set list(l) {
    if (l && l.nativeElement.ios) {
      l.nativeElement.ios.allowsSelection = false;
    }
  }
}
```

`Component.html`
```
<ListView #list>
  <CardItem>...
```

The underlying UITableView on iOS trying to allow selection of the card is what is causing the background to become transparent.
