### ISSUE TITLE
Not working with nativescript-vue

### ISSUE THREAD

**Issue by ghost** [bradmartin/nativescript-cardview#79]
Registering the component seems to be fine
`Vue.registerElement('CardView', () => require('nativescript-cardview').CardView)`

But when using it it will give this error:

```
System.err: Error: A Frame must be used to navigate to a Page.
System.err: File: "file:///data/data/me.konrad.popcorn/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/me.konrad.popcorn/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/me.konrad.popcorn/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     at android.app.Activity.performCreate(Activity.java:6955)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
System.err:     ... 10 more
```

**Comment by klever34** [comment]
@ghost were you able to solve the issue?

**Comment by rigor789** [comment]
@ghost can you show a bit more of your code and some information about your project? 

I'm mostly interested if you are using the vue-cli-template, and what features of it are you using (router, vuex etc).

This will help us identify the problem a bit quicker

**Comment by ghost** [comment]
I use NativeScript-Vue 1.3.1, nativescript-cardview 2.0.5, vue-router 3.0.1, tns-core-modules 3.4.1
I need a solution !

**Comment by Branded89** [comment]
Running into this issue as well. Default NativeScript-Vue setup.

Tried to create a new view, eg.
ExHome.vue
ExHome.js
ExHome.html

where ExHome.vue has the following content:

<template src="./ExHome.html"></template>
<script src="./ExHome.js"></script>

**Comment by dashmaker** [comment]
I have the same Error when trying to use nativescript-cardview with nativescript-vue. Has anyone found a solution?

**Comment by puffball1567** [comment]
CONSOLE WARN file:///app/tns_modules/tns-core-modules/ui/text-view/text-view.js:14:46: Class "UITextViewDelegateImpl" already implements the "UIScrollViewDelegate" protocol.


I soleved this error.
And then, nativescript-cardview is working.


npm install --save tns
npm install --save tns-core-modules

and

npm run clean


Please try.

**Comment by bradmartin** [comment]
Demo project has been added and working.
