### ISSUE TITLE
Dynamically create cards and append to StackLayout.

### ISSUE THREAD

**Issue by UD-UD** [bradmartin/nativescript-cardview#80]
Is there a way to create the cards dynamically and append them to a layout. I want something like

```js
let card = new Card();
/*
*Add various card data and styling
*/ 
stacklayout.append(card); // stacklayout is the reference to layout on the screen.
```

**Comment by BharathaAravind** [comment]
you can add cards as child to the layout.
In your case it would be something like stacklayout.addChild(card);
A whole example could be :
` var stk = page.getViewById('stackLayoutID');
var card = new CardView();
card.margin = 10;
card.radius = 5;
card.elevation = 40;
card.height = 40;
stk.addChild(card);`
