### ISSUE TITLE
Cardview not working

### ISSUE THREAD

**Issue by akhilbv1** [bradmartin/nativescript-cardview#82]
I have followed and done all the instructions and even removed platform and added and removed old build after adding plugin with tns-add but still receiving error:-TypeError: Could not load view for: CardView.TypeError: style.StylePropertyChangedHandler is not a constructor
JS: TypeError: Could not load view for: CardView.TypeError: style.StylePropertyChangedHandler is not a constructor
(Even registered in main.ts)
My nativescript version:-3.x

**Comment by bradmartin** [comment]
I've just updated the plugin, but did not encounter this with the demo application on android or iOS. Ping here and reopen if you are still getting the error.
