### ISSUE TITLE
not working for webpack build

### ISSUE THREAD

**Issue by Sumit-ignistec** [bradmartin/nativescript-cardview#83]
if I run with tns run build, i able to see carview, but if i run through webpack cardview not displaying

**Comment by shivgolani** [comment]
@Sumit-ignistec Any luck with the solution?

**Comment by bradmartin** [comment]
Any more info on this? Versions, any specific error reported?

**Comment by Lords08** [comment]
In my case, the solution was to insert this code in main.aot.ts file
`import { registerElement } from 'nativescript-angular/element-registry';
import { CardView } from 'nativescript-cardview';
registerElement('CardView', () => CardView);`
![image](https://user-images.githubusercontent.com/5959184/41770118-8b412b6c-763b-11e8-99e8-3f8af5269213.png)

Hopefully this can help you
