### ISSUE TITLE
CardView is not a constructor error

### ISSUE THREAD

**Issue by anaszgh** [bradmartin/nativescript-cardview#86]
Hello, 

I'm using CardView with TNS 4 & Angular,

but i'm receiving this error upon initializing the page that has the CardView
![screenshot_1527162496](https://user-images.githubusercontent.com/4104274/40483763-c66e2708-5f61-11e8-9132-f6d2984d106a.png)

**Comment by bradmartin** [comment]
Looks like a build issue that the library did not get bundled. Make sure to give this a read: https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/_

**Comment by Vetm** [comment]
Having the exact same problem as OP even after following the steps from your link.

**Comment by bradmartin** [comment]
Make sure to update your android build tools and support libs. I prefer android studio to manage the SDKs but can open the sdk manager via terminal also.

**Comment by anaszgh** [comment]
@bradmartin Thanks, that fixed it.

**Comment by Vetm** [comment]
That didn't do it for me. Using the nativescript angular template and newest Android SDK.
EDIT: Okay, [this](https://github.com/bradmartin/nativescript-cardview/issues/4#issuecomment-180329906) did the trick.

**Comment by carloscabral** [comment]
Hi, @bradmartin. I'm facing this error in NS Playground site. It works fine for iOS only. Any thoughts?

**Comment by bradmartin** [comment]
Don't know if adding native deps is supported by the playground. I would assume no for security reasons and technical challenges of allowing libs to be pulled in at random by adding a dependency to the playground project which would need to be compiled. iOS is all in JS so no native deps. @carloscabral hope that helps and makes sense 😄

**Comment by carloscabral** [comment]
It does make sense. Thank you, @bradmartin.

**Comment by marcossaore** [comment]
> Make sure to update your android build tools and support libs. I prefer android studio to manage the SDKs but can open the sdk manager via terminal also.

@bradmartin there is a way to do this works on NS Playground?

**Comment by marcossaore** [comment]
> It does make sense. Thank you, @bradmartin.

Fala @carloscabral , você conseguiu fazer isso funcionar no NS playground?
