### ISSUE TITLE
Android build fails with: String index out of range: -1

### ISSUE THREAD

**Issue by heese** [bradmartin/nativescript-cardview#90]
It seems that a value for 'productFlavors' is mandatory. I manually added the following code to 'android' in the file include.gradle.

```
    productFlavors {
        "nativescriptcardview" {
            dimension "nativescriptcardview"
        }
    }
```

Not sure though if is only my project setup. I am using NativeScript version 3.4.0.

**Comment by bradmartin** [comment]
https://github.com/bradmartin/nativescript-cardview#nativescript-3x
