### ISSUE TITLE
Overflow menu

### ISSUE THREAD

**Issue by StancuFlorin** [bradmartin/nativescript-cardview#92]
How can I add an overflow menu menu to my card?

![menu](https://material.io/design/assets/10o-Gi7QXR8JSHDdmCXuL9P8H3wAr2M2e/cards-overflowmenu-1b.png)

**Comment by bradmartin** [comment]
hmmm - I dont think the overflow menu is part of the cardview itself.

However, you can use a button in your cardview (in the layout), wire the tap event and use [this plugin](https://github.com/triniwiz/nativescript-popup) for something similar to the overflow menu. There are several other 'popup' type plugins that might provide a similar UX with some twists on them 😄 - hope that helps.
