### ISSUE TITLE
Android Elevation

### ISSUE THREAD

**Issue by darkmantle** [bradmartin/nativescript-cardview#93]
I have set the elevation property on the CardView, using NS Angular, yet there is no shadow **at all** on Android.

**Comment by karch4162** [comment]
I am seeing the same issue, no console errors but doesn't show shadow on Android. (Testing on Note 8)

```<CardView elevation="30" shadowOpacity="0.5" shadowColor="#000000" shadowOffsetHeight="2" shadowRadius="5" class="card-style">```

**Comment by visiblesoft-es** [comment]
Same problem for me, elevation is not working. Tested with Android emulator API 28.

**Comment by ppyoosuf** [comment]
same problem for me , `<CardView elevation="40" radius="5" ios:shadowRadius="3">` elevation is not working while test on Android device (API 24)

**Comment by bradmartin** [comment]
<img width="921" alt="elevation" src="https://user-images.githubusercontent.com/6006148/56074161-3ac32300-5d73-11e9-8e89-a57b6054d0f9.png">
Demo seems to be working 🤔 - Possibly something in the projects, maybe clashing support libs are causing problems in some projects. If someone can put together a simple demo reproducing this I'd be happy to look into it but I'm unable to repro currently.

**Comment by ppyoosuf** [comment]
now its working, problem was android:hardwareAccelerated="false" in AndroidManifest.xml. it should be true;
