### ISSUE TITLE
Any support for NativeScript 5?

### ISSUE THREAD

**Issue by COLTstreet** [bradmartin/nativescript-cardview#97]
I'm having issues using the CardView and I think it might be because I'm on 5.0. Just curious if this is support or not for NativeScript 5.

**Comment by bradmartin** [comment]
Shouldn't be any issues. I ran a test with the RC of 5x weeks ago. Do you have any error messages or crash logs? 

Might just be a situation where you need to update the support libs and android SDKs, then nuke your node_modules and platforms directory and rebuild the NS project. 

LMK if that helps any.

**Comment by COLTstreet** [comment]
So it looks like it works through the emulator after a build but tns preview won't work,

**Comment by lauhakari** [comment]
I'm having the same problem. When I do get to run in preview at all, the CardView just doesn't show up. Works in the Android emulator.

Oh and I'm using nativescript-vue, if that changes anything.

**Comment by bradmartin** [comment]
Forgot to circle back here. I don't use the preview app because I know it's limited to not being able to recompile since it's already a compiled android/ios app. So you can't load new libraries to the android/ios side.

Nothing the plugin can do.
